### ISSUE TITLE
Minor bug fixes on Mod mail, Code submission, Music cog

### ISSUE THREAD

**Issue by ryuga-hideki** [Tortoise-Community/Tortoise-BOT#72]
-music seems to have problem, The music stops a few seconds before its actually supposed to,
-code submission gives errors 
-modmail has a persisting issue apparently, Its does not seem to be working

**Comment by albertopoljak** [comment]
Music should be improved in #69 , from your description not sure what's the problem so will assume it's fixed by that PR.

Will open separate issue for code submission.

Modmail issue fixed in b1e520e

For future references please open multiple issues instead of dumping all into one, and be more descriptive e.g. `code submission gives errors` isn't very helpful.
